### ISSUE TITLE
Heatfluxes produced negative or complex values for CO2 concentration

### ISSUE THREAD

**Issue by cedsilva** [Christiaanvandertol/SCOPE#13]
I'm running SCOPE to produce a look up table over thousands of parameter combinations. For many parameter combinations (eg. Cab = 55; Vcmo = 85, LAI = 7; tts = 40; Rin = 600); the energy balance equations are failing when heafluxes.m is called in ebal.m, as the routine is producing negative CO2 concentrations.

I understand I need to run ebal.m, as I would like to simulate xanthophyll for PRI. 

Any suggestions for how to avoid this error? Are there reasons why particular parameter combinations might tend to produce this problem?

Any help you can offer is much appreciated!

Many thanks
Carlos E. Silva
Post-doc, Global Ecosystem Dynamics Investigation (GEDI)
University of Maryland

**Comment by cedsilva** [comment]
I might have written prematurely. I believe simply increasing the maximum iterations for ebal.m to allow time to find a proper solution has worked.

**Comment by Christiaanvandertol** [comment]
The energy balance closure routine (ebal) adjusts the leaf and soil temperatures until the net radiation matches with the non-radiative energy dissipation, using a Newton method. In some cases the energy balance fails to converge, and the model issues a warning message. Increasing the number of iterations or decreasing the step size (iter.Wc) can help. Good to hear that it did in your case.
If this does not solve the problem, then the model most likely has difficulty resolving the the aerodynamic resistance and atmospheric stability. Make sure the measurement height is well above the vegetation height, and d+z0m is less than the vegetation height, and preferably calculate z0m from LAI (options.calc_zo = 1).

**Comment by cedsilva** [comment]
Many thanks!! This is very helpful to know, as I continue building familiarity with the code and underlying calculations. Cheers!
