### ISSUE TITLE
Time serie simulation, directional angles

### ISSUE THREAD

**Issue by marinebouchet** [Christiaanvandertol/SCOPE#16]
Dear Prof. van der Tol,

At each time iteration, on calc_brdf l19 :

```
directional.psi = [directional.psi (at previous iteration); psi_hoversampling; psi_poversampling];  
directional.tto = [directional.tto (at previous iteration); tto_hoversampling; tto_poversampling];  
 ```
But keeping ```psi_hoversampling;psi_poversampling``` and ```tto_hoversampling;tto_poversampling``` of each previous iteration is a little bit useless I think.

It must be something like : 
```
directional.psi_iteration = [directional.psi (original psi); psi_hoversampling;psi_poversampling];  
directional.tto_iteration = [directional.tto (original tto); tto_hoversampling;tto_poversampling];
```
Many thanks!

Best regards,
Marine Bouchet from CESBIO, Toulouse, France

**Comment by Christiaanvandertol** [comment]
Dear Marine,
You may be the first one using multi-directional BRDF simulations in time series mode. Indeed 'directional.psi' and 'directional.tto' are growing inside the loop and this will increase the computation time. Indeed this can be solved as you suggest.
I would call the left side something like 'directional.psi_oversamping' and 'directional.tto_oversamping' to solve the issue. 
I will also add a comment lines to this function like the in other functions.
