### ISSUE TITLE
Error using load_timeseries (line 58)

### ISSUE THREAD

**Issue by bnulzq** [Christiaanvandertol/SCOPE#42]
I am running the SCOPE timeseries simulation with Matlab R2021a (Linux). The running error is:

Error using load_timeseries (line 59)
Comparison is not defined between double and datetime arrays.

Error in SCOPE (line 207)
    [V, xyt, mly_ts, atmo_paths]  = load_timeseries(V, F, xyt, path_input);

It seems like the format for the time variable t in the 'vegetation_retrieved_csv' (interpolatable.csv) and 'meteo_ec_csv' (ts_input.csv) are not same.

I printed the variables 't_int' and 't_' and found the t_int is in int/double format, while the t_ is in the date time format.

Do you know how to solve this error? Thank you!

**Comment by Prikaziuk** [comment]
Dear Zhenqi,

Thank you for the bug report! Indeed, interpolation_csv was not converting DOY to datetime. I believe it is corrected now, could you check with the develop branch code, please.

**Comment by bnulzq** [comment]
Thanks for your correction. However, I meet the new error in datetime converting:

Error using warning
Formatted arguments must be scalar.

Error in timestamp2datetime (line 14)
        warning('t is DOY, converting to date with year = %d, as `year` in .csv was empty', year_n)

Error in load_timeseries (line 24)
    t_ = timestamp2datetime(t_, year_n);

Error in SCOPE (line 207)
    [V, xyt, mly_ts, atmo_paths]  = load_timeseries(V, F, xyt, path_input);

**Comment by Prikaziuk** [comment]
This does not matter so much, it's about the formatting function. Nonetheless, corrected. Please, check again.

**Comment by bnulzq** [comment]
> This does not matter so much, it's about the formatting function. Nonetheless, corrected. Please, check again.

I am testing with the sample data 'ts_input' and 'interpolatable.csv'. With the updated develop branch, I got the error:

Error using datenum (line 201)
DATENUM failed.

Error in timestamp2datetime (line 13)
        ts = datestr(datenum(year_n, 0, ts), 'yyyymmddHHMMSS.FFF');

Error in load_timeseries (line 48)
        t_int = timestamp2datetime(t_int, year_n);

Error in SCOPE (line 207)
    [V, xyt, mly_ts, atmo_paths]  = load_timeseries(V, F, xyt, path_input);

Caused by:
    Error using datenum (line 174)
    Input arguments to DATENUM must match in size or be scalars.

It is caused by the mismatch of year and day in interpolation.csv, and seems the 'year_n' is not updated. So I update the year_n as:  'year_n = df_int.(year_column)', then it can run the simulation.

Now I am trying to test with my own dataset, hoping it will also run smoothly!

**Comment by Prikaziuk** [comment]
So @bnulzq did it run smoothly?

**Comment by bnulzq** [comment]
> So @bnulzq did it run smoothly?

Yeah, it runs well. Now I am using your develop branch to simulate. Is there any other difference with the Main branch?
Thanks for all your help!

**Comment by Prikaziuk** [comment]
``develop'' is only 1 commit behind ``master'', the exactly your commit about time series reading.
