### ISSUE TITLE
Default Vcmax25 values

### ISSUE THREAD

**Issue by bnulzq** [Christiaanvandertol/SCOPE#43]
Dear Prof. Van der Tol and Prof. Yang,

I notice that the default values of Vcmax25 is 60 umol m-2 s-1. I wonder if there is a look-up table for default Vcmax25 at different biome types in SCOPE model?

Many thanks!
Zhenqi Luo from Soil and Crop Science, Cornell University

**Comment by Prikaziuk** [comment]
Dear Zhenqi,

In SCOPE 1.73 there was a table on the first sheet of Input_data.xlsx file with very approximate values per biomes.
![image](https://user-images.githubusercontent.com/9042145/194538191-aeed33f0-4771-45c4-a8e1-6c84c795de2a.png)

After some tests we may recommend the values from Table 3 of Groenendijk et al., 2011 doi: 10.1016/j.agrformet.2010.08.013.

In some time an update will follow.

Best regards,
Egor

**Comment by bnulzq** [comment]
> Dear Zhenqi,
> 
> In SCOPE 1.73 there was a table on the first sheet of Input_data.xlsx file with very approximate values per biomes. ![image](https://user-images.githubusercontent.com/9042145/194538191-aeed33f0-4771-45c4-a8e1-6c84c795de2a.png)
> 
> After some tests we may recommend the values from Table 3 of [Groenendijk et al., 2011](https://doi.org/10.1016/j.agrformet.2010.08.013)
> 
> In some time an update will follow.
> 
> Best regards, Egor

Table in [Groenendijk et al., 2011](https://doi.org/10.1016/j.agrformet.2010.08.013) looks great!

Thanks

**Comment by Prikaziuk** [comment]
Dear @bnulzq 

You may also take a look at the newly published article  [Prikaziuk et al., 2023](https://doi.org/10.1016/j.rse.2022.113324 )

Best regards,
Egor
