### ISSUE TITLE
Definition of photosynthesis

### ISSUE THREAD

**Issue by bnulzq** [Christiaanvandertol/SCOPE#44]
Dear Egor,

I want to check the definition of photosynthesis here. 

In your document, the photosynthesis is the net photosynthesis of canopy, not the gross/apparent photosynthesis. Since the definitions of **photosynthesis**:
**Net photosynthesis**  = _true photosynthesis – photorespiration - dark respiration_
**GPP** = **apparent photosynthesis** = _true photosynthesis - photorespiration_ 

To get the **apparent photosynthesis (GPP)**, I still need to add the term of **dark respiration (Rd)**.
Is that right?

Thanks,
Zhenqi Luo

**Comment by Prikaziuk** [comment]
Dear Zhenqi,

If to simulate GPP with SCOPE you should set Rdparam = 0, which will disable the dark respiration computation. 

Best regards,
Egor

**Comment by bnulzq** [comment]
> 

Thank you very much, I will set Rdparam = 0 to simulate the GPP.
