### ISSUE TITLE
Error in RTMo() output

### ISSUE THREAD

**Issue by bnulzq** [Christiaanvandertol/SCOPE#50]
In SCOPE.m the output of `RTMo()` is `[rad,gap,profiles]`, should it be the `[rad,gap,canopy,profiles]`? It does not matter unless I turn on the `options.calc_vert_profiles` to calculate and output the profiles. 

I also would like to ask how can I get the profiles of `fluorescence`, I do not find the related code in `RTMf`.

**Comment by Prikaziuk** [comment]
Thank you, Luo Zhenqi,
Corrected (finally).
This will only output profiles of aPAR in photon units. If you need other profiles, you can get them in a similar way, averaging sunlit and shaded leaf contribution by the gap fractions Po https://github.com/Christiaanvandertol/SCOPE/blob/c3c17296e940318c1f64abac63f7ff62d85c70b7/src/RTMs/RTMo.m#L390
(I guess your question was answered long time ago)
Best regards,
Egor
