### ISSUE TITLE
calc_brdf

### ISSUE THREAD

**Issue by lm-costa** [Christiaanvandertol/SCOPE#54]
I've recently started to work with SCOPE and needed to make directional simulations.
I had failed in the first tentatives, as a warning message I was receiving: "Error using calc_brdf Too many input arguments".
I looked up the calc_brdf from 'scr/supporting' and compared it with the arguments from line 456 in SCOPE.m
In the calc_brdf inside SCOPE.m code, there is an additional argument 'Kn', after I removed the simulation worked. 

Cheers

**Comment by Prikaziuk** [comment]
Dear Luis Miguel,
Thank you for the bug report. Very well spotted!
Corrected.
Best regards,
Egor
